### ISSUE TITLE
Primitive types not supported when specified with metadata

### ISSUE THREAD

**Issue by fmiguelez** [SRserves85/avro-to-python#25]
When trying to process an ADOC with "bytes" type following error is raised

```
	Traceback (most recent call last):
	  File "/home/fer/.local/bin/avro-to-python", line 8, in <module>
		sys.exit(main())
	  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 764, in __call__
		return self.main(*args, **kwargs)
	  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 717, in main
		rv = self.invoke(ctx)
	  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 956, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/home/fer/.local/lib/python3.10/site-packages/click/core.py", line 555, in invoke
		return callback(*args, **kwargs)
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/cli.py", line 33, in main
		reader.read()
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/reader/read.py", line 81, in read
		self._build_namespace_tree()
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/reader/read.py", line 163, in _build_namespace_tree
		_record_file(file, item, queue)
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/utils/avro/files/record.py", line 80, in _record_file
		field = _union_field(
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/utils/avro/types/union.py", line 58, in _union_field
		field_type = _get_field_type(
	  File "/home/fer/.local/lib/python3.10/site-packages/avro_to_python/utils/avro/types/type_factory.py", line 49, in _get_field_type
		raise ValueError(
	ValueError: bytes is not supported.

```

**Comment by fmiguelez** [comment]
Sample of failing AVSC. It is actually due to specifying a primitive type with metadata attached (as a complex type).

```
{
  "type" : "record",
  "name" : "RecordWithComplexPrimitive",
  "namespace" : "records",
  "fields" : [ {
    "name" : "binaryData",
    "type" : {
      "type" : "bytes",
      "java-class" : "[B"
    }
  } ]
}
```

Notice the primitive type `bytes` that is specified as a complex type. This is the format produced by reflection util in Java AVRO library.
